feat: allow specifying the text for motion1 and allow specifying range for motion2
gbprod/substitute.nvim pull request #67
Opened 2023-06-07 18:13 UTC by IndianBoy42

For the former the main use cases is using vim.fn.getreg or vim.fn.expand so we allow shorthands for that

For the latter the main use case is directly specifying "%" for everywhere. But it can also be used for using the visual range

2023-06-07 18:14 UTC, IndianBoy42 commented
closes #61

2023-06-12 10:08 UTC, gbprod commented
Thanks for that, I try to review this soon

2023-06-19 10:03 UTC, gbprod requested changes

2023-06-19 10:03 UTC, gbprod commented on lua/substitute/range.lua
> +  vim.api.nvim_feedkeys(range.create_replace_command(), "ni", true)
Can you explain why you switch to `ni` here ?

2023-06-19 10:17 UTC, IndianBoy42 commented on lua/substitute/range.lua
> +  vim.api.nvim_feedkeys(range.create_replace_command(), "ni", true)
Mainly I think preferring no remaps is a bit safer. 

Personally I use `;` to open the cmdline and usually just don't use `:` for anything. At one point i tried out mapping something else to `:` and realized it made this stop working. This is obviously an extremely niche case, I may be the only person in history to do this, but still. I struggle to think of what mappings someone would have that we'd want/need to have remaps here.

2023-06-19 10:18 UTC, IndianBoy42 commented on README.md
> +This allows you to control the range of the substitution other than using
maybe just point them to `:h [range]` rather than practically repeating it verbatim here?

2023-06-19 10:19 UTC, IndianBoy42 commented on README.md
> +For example, specifying `range = '%'` will make the substitution run over the
I think in the end that is the more elegant API, I wasn't sure about proposing/making breaking changes in a PR.

2023-06-19 10:20 UTC, IndianBoy42 commented on README.md
> +For example, specifying `range = '%'` will make the substitution run over the
How do you handle deprecations and breaking changes?

2023-07-03 10:49 UTC, gbprod commented on lua/substitute/range.lua
> +  vim.api.nvim_feedkeys(range.create_replace_command(), "ni", true)
Thanks for your explanations

2023-07-03 10:50 UTC, gbprod approved these changes

2023-07-03 10:51 UTC, merged

2023-07-03 11:03 UTC, gbprod commented
Thanks